name: permission_handler
description: Permission plugin for Flutter. This plugin provides a cross-platform (iOS, Android) API to request and check permissions.
version: 7.0.0
homepage: https://github.com/baseflowit/flutter-permission-handler

flutter:
  plugin:
    platforms:
      android:
        package: com.baseflow.permissionhandler
        pluginClass: PermissionHandlerPlugin
      ios:
        pluginClass: PermissionHandlerPlugin

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.2.4
  permission_handler_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.12.8"
